const PRESENTATION_GET_REQUEST = 'PRESENTATION_GET_REQUEST';
const PRESENTATION_GET_SUCCESS = 'PRESENTATION_GET_SUCCESS';
const PRESENTATION_GET_ERROR = 'PRESENTATION_GET_ERROR';
const SESSION_LIST_BY_DATE_REQUEST = 'SESSION_LIST_BY_DATE_REQUEST';
const SESSION_LIST_BY_DATE_SUCCESS = 'SESSION_LIST_BY_DATE_SUCCESS';
const SESSION_LIST_BY_DATE_ERROR = 'SESSION_LIST_BY_DATE_ERROR';
const TYPES_LIST_REQUEST = 'TYPES_LIST_REQUEST';
const TYPES_LIST_SUCCESS = 'TYPES_LIST_SUCCESS';
const TYPES_LIST_ERROR = 'TYPES_LIST_ERROR';

export default {
    PRESENTATION_GET_REQUEST,
    PRESENTATION_GET_SUCCESS,
    PRESENTATION_GET_ERROR,
    SESSION_LIST_BY_DATE_REQUEST,
    SESSION_LIST_BY_DATE_SUCCESS,
    SESSION_LIST_BY_DATE_ERROR,
    TYPES_LIST_REQUEST,
    TYPES_LIST_SUCCESS,
    TYPES_LIST_ERROR
};