const PRESENTATION_GET_REQUEST = 'PRESENTATION_GET_REQUEST';
const PRESENTATION_GET_SUCCESS = 'PRESENTATION_GET_SUCCESS';
const PRESENTATION_GET_ERROR = 'PRESENTATION_GET_ERROR';

const AUTHOR_GET_REQUEST = 'AUTHOR_GET_REQUEST';
const AUTHOR_GET_SUCCESS = 'AUTHOR_GET_SUCCESS';
const AUTHOR_GET_ERROR = 'AUTHOR_GET_ERROR';


const SESSION_LIST_BY_DATE_REQUEST = 'SESSION_LIST_BY_DATE_REQUEST';
const SESSION_LIST_BY_DATE_SUCCESS = 'SESSION_LIST_BY_DATE_SUCCESS';
const SESSION_LIST_BY_DATE_ERROR = 'SESSION_LIST_BY_DATE_ERROR';

const SESSION_LIST_BY_ROOM_ID_REQUEST = 'SESSION_LIST_BY_ROOM_ID_REQUEST';
const SESSION_LIST_BY_ROOM_ID_SUCCESS = 'SESSION_LIST_BY_ROOM_ID_SUCCESS';
const SESSION_LIST_BY_ROOM_ID_ERROR = 'SESSION_LIST_BY_ROOM_ID_ERROR';

const SESSION_LIST_BY_AUTHOR_HASH_REQUEST = 'SESSION_LIST_BY_AUTHOR_HASH_REQUEST';
const SESSION_LIST_BY_AUTHOR_HASH_SUCCESS = 'SESSION_LIST_BY_AUTHOR_HASH_SUCCESS';
const SESSION_LIST_BY_AUTHOR_HASH_ERROR = 'SESSION_LIST_BY_AUTHOR_HASH_ERROR';

const TYPES_LIST_REQUEST = 'TYPES_LIST_REQUEST';
const TYPES_LIST_SUCCESS = 'TYPES_LIST_SUCCESS';
const TYPES_LIST_ERROR = 'TYPES_LIST_ERROR';

const ROOMS_LIST_REQUEST = 'ROOMS_LIST_REQUEST';
const ROOMS_LIST_SUCCESS = 'ROOMS_LIST_SUCCESS';
const ROOMS_LIST_ERROR = 'ROOMS_LIST_ERROR';

const FIRST_CHARS_LIST_REQUEST = 'FIRST_CHARS_LIST_REQUEST';
const FIRST_CHARS_LIST_SUCCESS = 'FIRST_CHARS_LIST_SUCCESS';
const FIRST_CHARS_LIST_ERROR = 'FIRST_CHARS_LIST_ERROR';

const AUTHORS_BY_FIRST_CHAR_LIST_REQUEST = 'AUTHORS_BY_FIRST_CHAR_LIST_REQUEST';
const AUTHORS_BY_FIRST_CHAR_LIST_SUCCESS = 'AUTHORS_BY_FIRST_CHAR_LIST_SUCCESS';
const AUTHORS_BY_FIRST_CHAR_LIST_ERROR = 'AUTHORS_BY_FIRST_CHAR_LIST_ERROR';



export default {
    PRESENTATION_GET_REQUEST,
    PRESENTATION_GET_SUCCESS,
    PRESENTATION_GET_ERROR,
    AUTHOR_GET_REQUEST,
    AUTHOR_GET_SUCCESS,
    AUTHOR_GET_ERROR,
    SESSION_LIST_BY_DATE_REQUEST,
    SESSION_LIST_BY_DATE_SUCCESS,
    SESSION_LIST_BY_DATE_ERROR,
    SESSION_LIST_BY_ROOM_ID_REQUEST,
    SESSION_LIST_BY_ROOM_ID_SUCCESS,
    SESSION_LIST_BY_ROOM_ID_ERROR,
    SESSION_LIST_BY_AUTHOR_HASH_REQUEST,
    SESSION_LIST_BY_AUTHOR_HASH_SUCCESS,
    SESSION_LIST_BY_AUTHOR_HASH_ERROR,
    TYPES_LIST_REQUEST,
    TYPES_LIST_SUCCESS,
    TYPES_LIST_ERROR,
    ROOMS_LIST_REQUEST,
    ROOMS_LIST_SUCCESS,
    ROOMS_LIST_ERROR,
    FIRST_CHARS_LIST_REQUEST,
    FIRST_CHARS_LIST_SUCCESS,
    FIRST_CHARS_LIST_ERROR,
    AUTHORS_BY_FIRST_CHAR_LIST_REQUEST,
    AUTHORS_BY_FIRST_CHAR_LIST_SUCCESS,
    AUTHORS_BY_FIRST_CHAR_LIST_ERROR
};
